SISO: C_SISOmud.cpp File Reference
C_SISOmud.cpp File Reference
Matlab interface for SISO MUD module.
#include "itpp/itmex.h"
#include "SISO.h"
Functions
void mexFunction (int n_output, mxArray *output[], int n_input, const mxArray *input[])
Detailed Description
Matlab interface for SISO MUD module.
Matlab function declaration: extrinsic_data = C_SISOmud(rec_sig, apriori_data, ch_imp_response, prec_gen, sigma2, mud_method)
compilation command: mex -litpp -lacml C_SISOmud.cpp
Definition in file C_SISOmud.cpp.
Function Documentation
void mexFunction (int n_output, mxArray * output[], int n_input, const mxArray * input[])
Definition at line 15 of file C_SISOmud.cpp.
References apriori_data, extrinsic_data, tr::SISO::mud(), tr::SISO::set_impulse_response(), tr::SISO::set_mud_method(), tr::SISO::set_noise(), tr::SISO::set_precoder_generator(), and sigma2.