SISO: C_SISOdemapper.cpp File Reference
C_SISOdemapper.cpp File Reference
Matlab interface for SISO demapper module.
#include "itpp/itmex.h"
#include "SISO.h"
Functions
void mexFunction (int n_output, mxArray *output[], int n_input, const mxArray *input[])
Detailed Description
Matlab interface for SISO demapper module.
Matlab function declaration: extrinsic_data = C_SISOdemapper(rec_sig, apriori_data, ch_imp_response, sigma2, bits_per_symbol, constellation, bin_constellation, demapper_method) or extrinsic_data = C_SISOdemapper(rec_sig, apriori_data, ch_imp_response, sigma2, bits_per_symbol, constellation, bin_constellation, symbols_per_block, ST_gen1, ST_gen2, demapper_method)
compilation command: mex -litpp -lacml C_SISOdemapper.cpp
Definition in file C_SISOdemapper.cpp.
Function Documentation
void mexFunction (int n_output, mxArray * output[], int n_input, const mxArray * input[])
Definition at line 19 of file C_SISOdemapper.cpp.
References apriori_data, bin_constellation, bits_per_symbol, constellation, tr::SISO::demapper(), demapper_method, extrinsic_data, tr::SISO::set_constellation(), tr::SISO::set_demapper_method(), tr::SISO::set_impulse_response(), tr::SISO::set_noise(), tr::SISO::set_st_block_code(), and sigma2.