SISO: C_SISOsova.cpp File Reference
C_SISOsova.cpp File Reference
Matlab interface for SISO RSC module using SOVA.
#include "itpp/itmex.h"
#include "SISO.h"
Functions
void mexFunction (int n_output, mxArray *output[], int n_input, const mxArray *input[])
Detailed Description
Matlab interface for SISO RSC module using SOVA.
Matlab function declaration: extrinsic_data = C_SISOsova(intrinsic_coded, apriori_data, bin_gen, win_len)
compilation command: mex -litpp -lacml C_SISOsova.cpp
Definition in file C_SISOsova.cpp.
Function Documentation
void mexFunction (int n_output, mxArray * output[], int n_input, const mxArray * input[])
Definition at line 16 of file C_SISOsova.cpp.
References apriori_data, bin_gen, extrinsic_coded, extrinsic_data, map_metric, tr::SISO::rsc(), tr::SISO::set_generators(), tr::SISO::set_map_metric(), tr::SISO::set_viterbi_hard_output_flag(), and tr::SISO::set_viterbi_win_len().