SISO: tr::SISO Class Reference
tr::SISO Class Reference
Soft Input Soft Output (SISO) modules.
#include <SISO.h>
Public Member Functions
SISO ()
SISO class constructor
void set_map_metric (const std::string &in_MAP_metric)
Sets the metric for MAP algorithm (convolutional codes and multipath channels).
void set_precoder_generator (const itpp::bvec &in_prec_gen)
Sets the precoder generator polynomial for turbo equalizer.
void set_precoder_generator (const int &in_prec_gen, const int &constraint_length)
void set_generators (const itpp::bmat &in_gen)
Sets convolutional code generator polynomials.
void set_generators (const itpp::ivec &in_gen, const int &constraint_length)
void set_tail (const bool &in_tail)
Signals whether the trellis used in the MAP algorithm is terminated or not (only for convolutional codes and multipath channels).
void set_viterbi_win_len (const int &win_len)
Sets the length of the trellis used by the SOVA.
void set_sova_scaling_factor (const double &scaling_factor)
Sets the scaling factor used to normalize the reliability value computed by the SOVA.
void set_sova_threshold (const double &threshold)
Sets the threshold value used to limit the reliability value computed by SOVA.
void set_viterbi_scaling_factors (const double &matching_scaling_factor, const double &nonmatching_scaling_factor)
Sets the Viterbi algorithm scaling factors.
void set_viterbi_hard_output_flag (const bool &flag)
Sets the Viterbi algorithm hard output flag (true when only the hard output is needed).
void set_noise (const double &in_sigma2)
Sets Additive White Gaussian Noise variance for each dimension.
void set_impulse_response (const itpp::vec &h)
Sets channel impulse response for equalizer.
void set_impulse_response (const itpp::mat &H)
Sets channel impulse response for Multi-User Detectors.
void set_impulse_response (const itpp::cvec &h)
Sets the channel attenuations for demappers (when only a modulator is used).
void set_impulse_response (const itpp::cmat &cH)
Sets channel attenuations for demappers (when Space-Time codes are used).
void set_scrambler_pattern (const itpp::vec &phi)
Sets scrambler pattern.
void set_scrambler_pattern (const itpp::bvec &phi)
void set_mud_method (const std::string &method)
Sets Multi-User Detector method.
void set_constellation (const int &in_nb_bits_symb, const itpp::cvec &in_constellation, const itpp::bmat &in_bin_constellation)
Sets symbol constellation.
void set_constellation (const int &in_nb_bits_symb, const itpp::cvec &in_constellation, const itpp::ivec &in_int_constellation)
void set_st_block_code (const int &Q, const itpp::cmat &A, const itpp::cmat &B, const int &N)
Sets Space-Time block code parameters.
void set_demapper_method (const std::string &method)
Sets demapper method.
void rsc (itpp::vec &extrinsic_coded, itpp::vec &extrinsic_data, const itpp::vec &intrinsic_coded, const itpp::vec &apriori_data)
SISO decoder for RSC codes
void rsc (itpp::vec &extrinsic_coded, itpp::vec &extrinsic_data, const itpp::vec &intrinsic_coded, const itpp::vec &apriori_data, const bool &tail)
SISO decoder for RSC codes (tail is set through input)
void nsc (itpp::vec &extrinsic_coded, itpp::vec &extrinsic_data, const itpp::vec &intrinsic_coded, const itpp::vec &apriori_data)
SISO decoder for NSC codes
void nsc (itpp::vec &extrinsic_coded, itpp::vec &extrinsic_data, const itpp::vec &intrinsic_coded, const itpp::vec &apriori_data, const bool &tail)
SISO decoder for NSC codes (tail is set through input)
void equalizer (itpp::vec &extrinsic_data, const itpp::vec &rec_sig, const itpp::vec &apriori_data)
SISO equalizer
void equalizer (itpp::vec &extrinsic_data, const itpp::vec &rec_sig, const itpp::vec &apriori_data, const bool &tail)
SISO equalizer (tail is set through input)
void descrambler (itpp::vec &extrinsic_coded, itpp::vec &extrinsic_data, const itpp::vec &intrinsic_coded, const itpp::vec &apriori_data)
SISO descrambler
void mud (itpp::mat &extrinsic_data, const itpp::vec &rec_sig, const itpp::mat &apriori_data)
SISO Multi-User Detector
void demapper (itpp::vec &extrinsic_data, const itpp::cvec &rec_sig, const itpp::vec &apriori_data)
SISO demapper (when only a modulator is used)
void demapper (itpp::vec &extrinsic_data, const itpp::cmat &rec_sig, const itpp::vec &apriori_data)
SISO demapper (when Space-Time codes are used)
Private Member Functions
void rsc_logMAP (itpp::vec &extrinsic_coded, itpp::vec &extrinsic_data, const itpp::vec &intrinsic_coded, const itpp::vec &apriori_data)
SISO::rsc using logMAP algorithm.
void rsc_maxlogMAP (itpp::vec &extrinsic_coded, itpp::vec &extrinsic_data, const itpp::vec &intrinsic_coded, const itpp::vec &apriori_data)
SISO::rsc using maxlogMAP algorithm.
void rsc_sova (itpp::vec &extrinsic_data, const itpp::vec &intrinsic_coded, const itpp::vec &apriori_data, const int &win_len)
SISO::rsc using SOVA.
void rsc_viterbi (itpp::vec &extrinsic_coded, itpp::vec &extrinsic_data, const itpp::vec &intrinsic_coded, const itpp::vec &apriori_data, const int &win_len)
SISO::rsc using Viterbi algorithm.
void nsc_logMAP (itpp::vec &extrinsic_coded, itpp::vec &extrinsic_data, const itpp::vec &intrinsic_coded, const itpp::vec &apriori_data)
SISO::nsc using logMAP algorithm.
void nsc_maxlogMAP (itpp::vec &extrinsic_coded, itpp::vec &extrinsic_data, const itpp::vec &intrinsic_coded, const itpp::vec &apriori_data)
SISO::nsc using maxlogMAP algorithm.
void equalizer_logMAP (itpp::vec &extrinsic_data, const itpp::vec &rec_sig, const itpp::vec &apriori_data)
SISO::equalizer using logMAP algorithm.
void equalizer_maxlogMAP (itpp::vec &extrinsic_data, const itpp::vec &rec_sig, const itpp::vec &apriori_data)
SISO::equalizer using maxlogMAP algorithm.
void mud_maxlogMAP (itpp::mat &extrinsic_data, const itpp::vec &rec_sig, const itpp::mat &apriori_data)
SISO::mud using maxlogMAP algorithm.
void mud_maxlogTMAP (itpp::mat &extrinsic_data, const itpp::vec &rec_sig, const itpp::mat &apriori_data, const double &threshold=-5)
SISO::mud using maxlogMAP algorithm based on T-BCJR.
void GCD (itpp::mat &extrinsic_data, const itpp::vec &rec_sig, const itpp::mat &apriori_data)
SISO::mud using Gaussian Chip Detector (GCD).
void sGCD (itpp::mat &extrinsic_data, const itpp::vec &rec_sig, const itpp::mat &apriori_data)
SISO::mud using simplified Gaussian Chip Detector (sGCD).
void Hassibi_maxlogMAP (itpp::vec &extrinsic_data, const itpp::cmat &rec_sig, const itpp::vec &apriori_data)
SISO::demapper using maxlogMAP algorithm for ST block codes described using Hassibi's model.
void GA (itpp::vec &extrinsic_data, const itpp::cmat &rec_sig, const itpp::vec &apriori_data)
SISO::demapper using Gaussian Approximation (GA) algorithm.
void sGA (itpp::vec &extrinsic_data, const itpp::cmat &rec_sig, const itpp::vec &apriori_data)
SISO::demapper using simplified Gaussian Approximation (sGA) algorithm.
void mmsePIC (itpp::vec &extrinsic_data, const itpp::cmat &rec_sig, const itpp::vec &apriori_data)
SISO::demapper using MMSE Parallel Interference Canceller (PIC).
void zfPIC (itpp::vec &extrinsic_data, const itpp::cmat &rec_sig, const itpp::vec &apriori_data)
SISO::demapper using ZF Parallel Interference Canceller (PIC).
void Alamouti_maxlogMAP (itpp::vec &extrinsic_data, const itpp::cmat &rec_sig, const itpp::vec &apriori_data)
SISO::demapper using maxlogMAP algorithm and matched filter receiver for Alamouti ST code.
void demodulator_logMAP (itpp::vec &extrinsic_data, const itpp::cvec &rec_sig, const itpp::vec &apriori_data)
SISO::demapper using logMAP algorithm for complex modulators.
void demodulator_maxlogMAP (itpp::vec &extrinsic_data, const itpp::cvec &rec_sig, const itpp::vec &apriori_data)
SISO::demapper using maxlogMAP algorithm for complex modulators.
void print_err_msg (const std::string &msg) const
Prints an error message to standard output.
void zpFIRfilter (itpp::vec &filt, const itpp::vec &h, const itpp::vec &sig)
FIR filter for a zero padded signals (zeros are added at the end of the signal, where is the order of the filter).
void gen_chtrellis (void)
Generates (precoded) channel trellis.
void gen_hyperTrellis (void)
Generates (precoded) hyper channel trellis.
void gen_rsctrellis (void)
Generates Recursive and Systematic Convolutional (RSC) code trellis.
void gen_nsctrellis (void)
Generates Non recursive and non Systematic Convolutional (NSC) code trellis.
void find_half_const (int &select_half, itpp::vec &re_part, itpp::bmat &re_bin_part, itpp::vec &im_part, itpp::bmat &im_bin_part)
Finds half constellations.
void EquivRecSig (itpp::vec &x_eq, const itpp::cmat &rec_sig)
Finds equivalent received signal with real coefficients.
void EquivCh (itpp::mat &H_eq, const itpp::cvec &H)
Finds equivalent channel with real coefficients.
Private Attributes
std::string MAP_metric
MAP algorithm metric.
itpp::bmat gen
Generator polynomials for convolutional codes (CC).
itpp::bvec prec_gen
Precoder generator polynomial.
bool tail
True if trellis of CC is terminated.
int Viterbi_win_len
Viterbi trellis window length.
double SOVA_scaling_factor
SOVA scaling factor used to multiply the reliabiliy information.
double SOVA_threshold
SOVA threshold used to limit the reliability information.
double Viterbi_scaling_factor [2]
Viterbi scaling factors.
bool Viterbi_hard_output_flag
Viterbi hard output flag (true when only hard output is needed).
double sigma2
AWGN noise variance.
itpp::mat impulse_response
Real channel impulse response.
itpp::cmat c_impulse_response
Complex channel impulse response.
itpp::bvec scrambler_pattern
Scrambler pattern.
std::string MUD_method
MUD method.
int nb_bits_symb
Number of bits/symbol.
itpp::cvec constellation
Complex constellation.
itpp::bmat bin_constellation
Binary constellation.
int symbols_block
Number of symbols/block.
int nb_em_ant
Number of emission antennas.
int nb_rec_ant
Number of reception antennas.
int block_duration
ST code block duration.
itpp::cmat ST_gen1
ST generator matrix 1.
itpp::cmat ST_gen2
ST generator matrix 2.
std::string demapper_method
Demapper method.
struct {
int numInputSymbols
number of input symbols
int stateNb
number of states
int * prevState
previous states
int * nextState
next states
double * output
output
int * input
input
} chtrellis
(Hyper) Channel trellis
struct {
int numStates
number of states
int * prevStates
previous states
int * nextStates
next states
double * PARout
parity output bit
itpp::bin * fm
} rsctrellis
RSC code trellis.
struct {
int stateNb
number of states
int * prevState
previous states
int * nextState
next states
double * output
output
int * input
input
} nsctrellis
NSC code trellis.
Detailed Description
Soft Input Soft Output (SISO) modules.
The following SISO modules are implemented:
decoder for an Recursive Systematic Convolutional (RSC) code
decoder for an Non-recursive non-Systematic Convolutional (NSC) code
equalizer (without and with precoding)
descrambler used in Interleave Division Multiple Access (IDMA) systems
Multi User Detectors (MUDs) for IDMA systems
demappers for Bit Interleaved Coded Modulation (BICM) systems
demappers for Space Time (ST) BICM systems
BPSK mapping is realized as follows: 0 -> +1 and 1 -> -1. Thus the xor truth table is preserved when multiplying BPSK symbols.
Definition at line 31 of file SISO.h.
Constructor & Destructor Documentation
tr::SISO::SISO () [inline]
SISO class constructor
Internal variables are initialized with default values:
the trellis used in MAP algorithm is not terminated
maxlogMAP metric is used
simplified GCD is selected
no scrambler is used
GA demapper is selected
Definition at line 412 of file SISO.h.
References demapper_method, MAP_metric, MUD_method, prec_gen, scrambler_pattern, SOVA_scaling_factor, SOVA_threshold, tail, Viterbi_hard_output_flag, Viterbi_scaling_factor, and Viterbi_win_len.
Member Function Documentation
void tr::SISO::Alamouti_maxlogMAP (itpp::vec & extrinsic_data, const itpp::cmat & rec_sig, const itpp::vec & apriori_data) [private]
SISO::demapper using maxlogMAP algorithm and matched filter receiver for Alamouti ST code.
Definition at line 693 of file SISO_dem.cpp.
References apriori_data, bin_constellation, c_impulse_response, constellation, extrinsic_data, n, nb_bits_symb, nb_rec_ant, nb_symb, sigma2, and temp.
Referenced by demapper().
void tr::SISO::demapper (itpp::vec & extrinsic_data, const itpp::cmat & rec_sig, const itpp::vec & apriori_data) [inline]
SISO demapper (when Space-Time codes are used)
Parameters:
extrinsic_data extrinsic informations of emitted bits
rec_sig received signal
apriori_data a priori informations of emitted bits
Definition at line 711 of file SISO.h.
References Alamouti_maxlogMAP(), bin_constellation, c_impulse_response, constellation, demapper_method, GA(), Hassibi_maxlogMAP(), mmsePIC(), print_err_msg(), sGA(), ST_gen1, ST_gen2, and zfPIC().
void tr::SISO::demapper (itpp::vec & extrinsic_data, const itpp::cvec & rec_sig, const itpp::vec & apriori_data) [inline]
SISO demapper (when only a modulator is used)
Parameters:
extrinsic_data extrinsic informations of emitted bits
rec_sig received signal
apriori_data a priori informations of emitted bits
Definition at line 690 of file SISO.h.
References bin_constellation, c_impulse_response, constellation, demodulator_logMAP(), demodulator_maxlogMAP(), MAP_metric, and print_err_msg().
Referenced by main(), and mexFunction().
void tr::SISO::demodulator_logMAP (itpp::vec & extrinsic_data, const itpp::cvec & rec_sig, const itpp::vec & apriori_data) [private]
SISO::demapper using logMAP algorithm for complex modulators.
logMAP demodulator
Definition at line 742 of file SISO_dem.cpp.
References apriori_data, bin_constellation, c_impulse_response, constellation, extrinsic_data, nb_bits_symb, nb_symb, sigma2, and temp.
Referenced by demapper().
void tr::SISO::demodulator_maxlogMAP (itpp::vec & extrinsic_data, const itpp::cvec & rec_sig, const itpp::vec & apriori_data) [private]
SISO::demapper using maxlogMAP algorithm for complex modulators.
maxlogMAP demodulator
Definition at line 772 of file SISO_dem.cpp.
References apriori_data, bin_constellation, c_impulse_response, constellation, extrinsic_data, nb_bits_symb, nb_symb, sigma2, and temp.
Referenced by demapper().
void tr::SISO::descrambler (itpp::vec & extrinsic_coded, itpp::vec & extrinsic_data, const itpp::vec & intrinsic_coded, const itpp::vec & apriori_data)
SISO descrambler
Parameters:
extrinsic_coded extrinsic information of scrambled bits
extrinsic_data extrinsic information of informational bits
intrinsic_coded intrinsic information of scrambled bits
apriori_data a priori information of informational bits
Definition at line 10 of file SISO_mud.cpp.
References n, nb_bits, and scrambler_pattern.
Referenced by main(), and mexFunction().
void tr::SISO::equalizer (itpp::vec & extrinsic_data, const itpp::vec & rec_sig, const itpp::vec & apriori_data, const bool & tail) [inline]
SISO equalizer (tail is set through input)
Channel trellis is generated so that BPSK mapping is assumed: 0->+1 and 1->-1 (xor truth table is preserved)
Parameters:
extrinsic_data extrinsic informations of input symbols
rec_sig received signal
apriori_data a priori informations of input symbols
tail if true the trellis is terminated
Definition at line 634 of file SISO.h.
References equalizer(), and set_tail().
void tr::SISO::equalizer (itpp::vec & extrinsic_data, const itpp::vec & rec_sig, const itpp::vec & apriori_data) [inline]
SISO equalizer
Channel trellis is generated so that BPSK mapping is assumed: 0->+1 and 1->-1 (xor truth table is preserved)
Parameters:
extrinsic_data extrinsic informations of input symbols
rec_sig received signal
apriori_data a priori informations of input symbols
Definition at line 644 of file SISO.h.
References equalizer_logMAP(), equalizer_maxlogMAP(), impulse_response, MAP_metric, prec_gen, and print_err_msg().
Referenced by equalizer(), main(), and mexFunction().
void tr::SISO::equalizer_logMAP (itpp::vec & extrinsic_data, const itpp::vec & rec_sig, const itpp::vec & apriori_data) [private]
SISO::equalizer using logMAP algorithm.
Definition at line 77 of file SISO_eq.cpp.
References chtrellis, gen_chtrellis(), n, sigma2, and tail.
Referenced by equalizer().
void tr::SISO::equalizer_maxlogMAP (itpp::vec & extrinsic_data, const itpp::vec & rec_sig, const itpp::vec & apriori_data) [private]
SISO::equalizer using maxlogMAP algorithm.
Definition at line 192 of file SISO_eq.cpp.
References chtrellis, gen_chtrellis(), if(), n, sigma2, and tail.
Referenced by equalizer().
void tr::SISO::EquivCh (itpp::mat & H_eq, const itpp::cvec & H) [private]
Finds equivalent channel with real coefficients.
Definition at line 93 of file SISO_dem.cpp.
References block_duration, n, nb_em_ant, nb_rec_ant, ST_gen1, ST_gen2, symbols_block, and temp.
Referenced by GA(), Hassibi_maxlogMAP(), mmsePIC(), sGA(), and zfPIC().
void tr::SISO::EquivRecSig (itpp::vec & x_eq, const itpp::cmat & rec_sig) [private]
Finds equivalent received signal with real coefficients.
Definition at line 78 of file SISO_dem.cpp.
References block_duration, and nb_rec_ant.
Referenced by GA(), Hassibi_maxlogMAP(), mmsePIC(), sGA(), and zfPIC().
void tr::SISO::find_half_const (int & select_half, itpp::vec & re_part, itpp::bmat & re_bin_part, itpp::vec & im_part, itpp::bmat & im_bin_part) [private]
Finds half constellations.
Definition at line 10 of file SISO_dem.cpp.
References bin_constellation, constellation, n, nb_bits_symb, print_err_msg(), and temp.
Referenced by GA(), mmsePIC(), sGA(), and zfPIC().
void tr::SISO::GA (itpp::vec & extrinsic_data, const itpp::cmat & rec_sig, const itpp::vec & apriori_data) [private]
SISO::demapper using Gaussian Approximation (GA) algorithm.
Definition at line 183 of file SISO_dem.cpp.
References apriori_data, block_duration, c_impulse_response, EquivCh(), EquivRecSig(), extrinsic_data, find_half_const(), nb_bits_symb, nb_rec_ant, sigma2, symbols_block, and temp.
Referenced by demapper().
void tr::SISO::GCD (itpp::mat & extrinsic_data, const itpp::vec & rec_sig, const itpp::mat & apriori_data) [private]
SISO::mud using Gaussian Chip Detector (GCD).
Gaussian Chip Detector for IDMA systems.
Use with care for large size of interleavers.
Definition at line 306 of file SISO_mud.cpp.
References extrinsic_data, impulse_response, n, and print_err_msg().
Referenced by mud().
void tr::SISO::gen_chtrellis (void) [private]
Generates (precoded) channel trellis.
Definition at line 10 of file SISO_eq.cpp.
References chtrellis, impulse_response, n, and prec_gen.
Referenced by equalizer_logMAP(), and equalizer_maxlogMAP().
void tr::SISO::gen_hyperTrellis (void) [private]
Generates (precoded) hyper channel trellis.
Definition at line 69 of file SISO_mud.cpp.
References chtrellis, impulse_response, n, prec_gen, and print_err_msg().
Referenced by mud_maxlogMAP().
void tr::SISO::gen_nsctrellis (void) [private]
Generates Non recursive and non Systematic Convolutional (NSC) code trellis.
Definition at line 10 of file SISO_nsc.cpp.
References gen, n, and nsctrellis.
Referenced by nsc_logMAP(), and nsc_maxlogMAP().
void tr::SISO::gen_rsctrellis (void) [private]
Generates Recursive and Systematic Convolutional (RSC) code trellis.
Definition at line 10 of file SISO_rsc.cpp.
References gen, n, and rsctrellis.
Referenced by rsc_logMAP(), rsc_maxlogMAP(), rsc_sova(), and rsc_viterbi().
void tr::SISO::Hassibi_maxlogMAP (itpp::vec & extrinsic_data, const itpp::cmat & rec_sig, const itpp::vec & apriori_data) [private]
SISO::demapper using maxlogMAP algorithm for ST block codes described using Hassibi's model.
Definition at line 129 of file SISO_dem.cpp.
References apriori_data, block_duration, c_impulse_response, constellation, EquivCh(), EquivRecSig(), extrinsic_data, n, nb_bits_symb, nb_rec_ant, sigma2, symbols_block, and temp.
Referenced by demapper().
void tr::SISO::mmsePIC (itpp::vec & extrinsic_data, const itpp::cmat & rec_sig, const itpp::vec & apriori_data) [private]
SISO::demapper using MMSE Parallel Interference Canceller (PIC).
Definition at line 438 of file SISO_dem.cpp.
References apriori_data, block_duration, c_impulse_response, EquivCh(), EquivRecSig(), Es, extrinsic_data, find_half_const(), nb_bits_symb, nb_em_ant, nb_rec_ant, sigma2, symbols_block, and temp.
Referenced by demapper().
void tr::SISO::mud (itpp::mat & extrinsic_data, const itpp::vec & rec_sig, const itpp::mat & apriori_data) [inline]
SISO Multi-User Detector
Parameters:
extrinsic_data extrinsic informations of emitted chips from all users
rec_sig received signal
apriori_data a priori informations of emitted chips from all users
Definition at line 666 of file SISO.h.
References GCD(), impulse_response, mud_maxlogMAP(), MUD_method, print_err_msg(), and sGCD().
Referenced by main(), and mexFunction().
void tr::SISO::mud_maxlogMAP (itpp::mat & extrinsic_data, const itpp::vec & rec_sig, const itpp::mat & apriori_data) [private]
SISO::mud using maxlogMAP algorithm.
Maximum A Posteriori algorithm for Multi-User Detection in IDMA systems.
uses max log MAP algorithm use with care for large number of users and/or FIR channel order
Definition at line 166 of file SISO_mud.cpp.
References apriori_data, chtrellis, extrinsic_data, gen_hyperTrellis(), n, print_err_msg(), sigma2, and tail.
Referenced by mud().
void tr::SISO::mud_maxlogTMAP (itpp::mat & extrinsic_data, const itpp::vec & rec_sig, const itpp::mat & apriori_data, const double & threshold = -5) [private]
SISO::mud using maxlogMAP algorithm based on T-BCJR.
void tr::SISO::nsc (itpp::vec & extrinsic_coded, itpp::vec & extrinsic_data, const itpp::vec & intrinsic_coded, const itpp::vec & apriori_data, const bool & tail) [inline]
SISO decoder for NSC codes (tail is set through input)
Parameters:
extrinsic_coded extrinsic information of coded bits
extrinsic_data extrinsic information of data bits
intrinsic_coded intrinsic information of coded bits
apriori_data a priori information of data bits
tail if true the trellis is terminated
Definition at line 610 of file SISO.h.
References nsc(), and set_tail().
void tr::SISO::nsc (itpp::vec & extrinsic_coded, itpp::vec & extrinsic_data, const itpp::vec & intrinsic_coded, const itpp::vec & apriori_data) [inline]
SISO decoder for NSC codes
Parameters:
extrinsic_coded extrinsic information of coded bits
extrinsic_data extrinsic information of data bits
intrinsic_coded intrinsic information of coded bits
apriori_data a priori information of data bits
Definition at line 617 of file SISO.h.
References gen, MAP_metric, nsc_logMAP(), nsc_maxlogMAP(), and print_err_msg().
Referenced by main(), mexFunction(), and nsc().
void tr::SISO::nsc_logMAP (itpp::vec & extrinsic_coded, itpp::vec & extrinsic_data, const itpp::vec & intrinsic_coded, const itpp::vec & apriori_data) [private]
SISO::nsc using logMAP algorithm.
Definition at line 81 of file SISO_nsc.cpp.
References gen, gen_nsctrellis(), n, nsctrellis, scrambler_pattern, and tail.
Referenced by nsc().
void tr::SISO::nsc_maxlogMAP (itpp::vec & extrinsic_coded, itpp::vec & extrinsic_data, const itpp::vec & intrinsic_coded, const itpp::vec & apriori_data) [private]
SISO::nsc using maxlogMAP algorithm.
Definition at line 273 of file SISO_nsc.cpp.
References gen, gen_nsctrellis(), n, nsctrellis, scrambler_pattern, and tail.
Referenced by nsc().
void tr::SISO::print_err_msg (const std::string & msg) const [inline, private]
Prints an error message to standard output.
If the SISO class is used in a mex file, this function ensures that the proper function is used for displaying the error message
Definition at line 746 of file SISO.h.
Referenced by demapper(), equalizer(), find_half_const(), GCD(), gen_hyperTrellis(), mud(), mud_maxlogMAP(), nsc(), and rsc().
void tr::SISO::rsc (itpp::vec & extrinsic_coded, itpp::vec & extrinsic_data, const itpp::vec & intrinsic_coded, const itpp::vec & apriori_data, const bool & tail) [inline]
SISO decoder for RSC codes (tail is set through input)
Parameters:
extrinsic_coded extrinsic information of parity bits
extrinsic_data extrinsic information of data bits
intrinsic_coded intrinsic information of coded bits
apriori_data a priori information of data bits
tail if true the trellis is terminated
Definition at line 575 of file SISO.h.
References rsc(), and set_tail().
void tr::SISO::rsc (itpp::vec & extrinsic_coded, itpp::vec & extrinsic_data, const itpp::vec & intrinsic_coded, const itpp::vec & apriori_data) [inline]
SISO decoder for RSC codes
Parameters:
extrinsic_coded extrinsic information of parity bits
extrinsic_data extrinsic information of data bits
intrinsic_coded intrinsic information of coded bits
apriori_data a priori information of data bits
Definition at line 582 of file SISO.h.
References gen, MAP_metric, print_err_msg(), rsc_logMAP(), rsc_maxlogMAP(), rsc_sova(), rsc_viterbi(), and Viterbi_win_len.
Referenced by main(), mexFunction(), and rsc().
void tr::SISO::rsc_logMAP (itpp::vec & extrinsic_coded, itpp::vec & extrinsic_data, const itpp::vec & intrinsic_coded, const itpp::vec & apriori_data) [private]
SISO::rsc using logMAP algorithm.
Definition at line 60 of file SISO_rsc.cpp.
References gen_rsctrellis(), n, rsctrellis, and tail.
Referenced by rsc().
void tr::SISO::rsc_maxlogMAP (itpp::vec & extrinsic_coded, itpp::vec & extrinsic_data, const itpp::vec & intrinsic_coded, const itpp::vec & apriori_data) [private]
SISO::rsc using maxlogMAP algorithm.
Definition at line 228 of file SISO_rsc.cpp.
References gen_rsctrellis(), n, rsctrellis, and tail.
Referenced by rsc().
void tr::SISO::rsc_sova (itpp::vec & extrinsic_data, const itpp::vec & intrinsic_coded, const itpp::vec & apriori_data, const int & win_len) [private]
SISO::rsc using SOVA.
Parameters:
extrinsic_data extrinsic information of data bits
intrinsic_coded intrinsic information of coded bits
apriori_data a priori information of data bits
win_len window length used to represent the trellis
Definition at line 390 of file SISO_rsc.cpp.
References apriori_data, extrinsic_data, gen, gen_rsctrellis(), rsctrellis, SOVA_scaling_factor, SOVA_threshold, and tr::threshold().
Referenced by rsc().
void tr::SISO::rsc_viterbi (itpp::vec & extrinsic_coded, itpp::vec & extrinsic_data, const itpp::vec & intrinsic_coded, const itpp::vec & apriori_data, const int & win_len) [private]
SISO::rsc using Viterbi algorithm.
Parameters:
extrinsic_coded extrinsic information of coded bits
extrinsic_data extrinsic information of data bits
intrinsic_coded intrinsic information of coded bits
apriori_data a priori information of data bits
win_len window length used to represent the trellis
Definition at line 561 of file SISO_rsc.cpp.
References apriori_data, extrinsic_coded, extrinsic_data, gen, gen_rsctrellis(), rsctrellis, Viterbi_hard_output_flag, and Viterbi_scaling_factor.
Referenced by rsc().
void tr::SISO::set_constellation (const int & in_nb_bits_symb, const itpp::cvec & in_constellation, const itpp::ivec & in_int_constellation) [inline]
Parameters:
in_nb_bits_symb the number of symbols
in_constellation all possible symbols as a complex vector
in_int_constellation integer representations of symbols as a vector
Definition at line 545 of file SISO.h.
References bin_constellation, constellation, n, nb_bits_symb, and nb_symb.
void tr::SISO::set_constellation (const int & in_nb_bits_symb, const itpp::cvec & in_constellation, const itpp::bmat & in_bin_constellation) [inline]
Sets symbol constellation.
The correspondence between each symbol and its binary representation is given.
Parameters:
in_nb_bits_symb the number of symbols
in_constellation all possible symbols as a complex vector
in_bin_constellation binary representations of symbols as a binary matrix (each row corresponds to one symbol)
Definition at line 537 of file SISO.h.
References bin_constellation, constellation, and nb_bits_symb.
Referenced by main(), and mexFunction().
void tr::SISO::set_demapper_method (const std::string & method) [inline]
Sets demapper method.
Possible input values are:
Hassibi_MAP (maxlogMAP algorithm applied for ST block codes represented using Hassibi's model)
GA
sGA (simplified GA)
mmsePIC
zfPIC (simplified mmsePIC)
Alamouti_MAP (maxlogMAP algorithm applied to Alamouti code using matched-filter reception method)
Definition at line 570 of file SISO.h.
References demapper_method.
Referenced by main(), and mexFunction().
void tr::SISO::set_generators (const itpp::ivec & in_gen, const int & constraint_length) [inline]
Definition at line 449 of file SISO.h.
References gen, and n.
void tr::SISO::set_generators (const itpp::bmat & in_gen) [inline]
Sets convolutional code generator polynomials.
The generator polynomials are specified as rows of the input binary matrix.
Definition at line 444 of file SISO.h.
References gen.
Referenced by main(), and mexFunction().
void tr::SISO::set_impulse_response (const itpp::cmat & cH) [inline]
Sets channel attenuations for demappers (when Space-Time codes are used).
The input is a complex matrix of dimension , where and is the number of emission and reception antennas, respectively and is the transmission duration expressed in symbol durations.
This input matrix is formed as follows:
the starting point is an complex matrix (channel matrix) with one row represented by the atenuations seen by each of reception antennas during one symbol duration, when the signal is emitted by a given emission antenna. The row number represents the number of emission antenna.
the channel matrix is then transformed into a vector of length , with the first elements the first column of the channel matrix
the vector of length represents one column of the input matrix
in the input matrix, the vector is repeated times and different vectors are used. Thus, the channel is supposed constant over symbol durations (channel coherence time) and different channel realisations are used.
in our implementation must be and integer multiple of , where is the ST block code duration expressed in symbol durations. This means that the channel matrix must be constant over at least symbol durations.
Definition at line 512 of file SISO.h.
References c_impulse_response.
void tr::SISO::set_impulse_response (const itpp::cvec & h) [inline]
Sets the channel attenuations for demappers (when only a modulator is used).
The input is the vector of channel attenuations for each received symbol
Definition at line 506 of file SISO.h.
References c_impulse_response.
void tr::SISO::set_impulse_response (const itpp::mat & H) [inline]
Sets channel impulse response for Multi-User Detectors.
The input is a real matrix with each row represented by the channel impulse response of one user.
Definition at line 501 of file SISO.h.
References impulse_response.
void tr::SISO::set_impulse_response (const itpp::vec & h) [inline]
Sets channel impulse response for equalizer.
The input is a real channel impulse response.
Definition at line 495 of file SISO.h.
References impulse_response.
Referenced by main(), and mexFunction().
void tr::SISO::set_map_metric (const std::string & in_MAP_metric) [inline]
Sets the metric for MAP algorithm (convolutional codes and multipath channels).
Possible input values are:
logMAP
maxlogMAP
SOVA
Viterbi Soft Output Viterbi Algorithm (SOVA) is equivalent to the MAP algorithm only when the a priori information is zero.
Definition at line 428 of file SISO.h.
References MAP_metric.
Referenced by main(), and mexFunction().
void tr::SISO::set_mud_method (const std::string & method) [inline]
Sets Multi-User Detector method.
Possible input values are:
maxlogMAP
maxlogTMAP
GCD
sGCD (simplified GCD)
Definition at line 532 of file SISO.h.
References MUD_method.
Referenced by main(), and mexFunction().
void tr::SISO::set_noise (const double & in_sigma2) [inline]
Sets Additive White Gaussian Noise variance for each dimension.
Definition at line 490 of file SISO.h.
References sigma2.
Referenced by main(), and mexFunction().
void tr::SISO::set_precoder_generator (const int & in_prec_gen, const int & constraint_length) [inline]
Definition at line 438 of file SISO.h.
References prec_gen.
void tr::SISO::set_precoder_generator (const itpp::bvec & in_prec_gen) [inline]
Sets the precoder generator polynomial for turbo equalizer.
The precoder is used in turbo equalization. The generator polynomial describes the feedback connections of the precoder.
Definition at line 433 of file SISO.h.
References prec_gen.
Referenced by main(), and mexFunction().
void tr::SISO::set_scrambler_pattern (const itpp::bvec & phi) [inline]
Definition at line 527 of file SISO.h.
References scrambler_pattern.
void tr::SISO::set_scrambler_pattern (const itpp::vec & phi) [inline]
Sets scrambler pattern.
The scrambler pattern must be a sequence of and is used by the SISO NSC module in IDMA systems reception. At emission side the bits are first encoded by an NSC code, BPSK modulated and then scrambled with the given pattern.
Definition at line 517 of file SISO.h.
References n, and scrambler_pattern.
Referenced by main(), and mexFunction().
void tr::SISO::set_sova_scaling_factor (const double & scaling_factor) [inline]
Sets the scaling factor used to normalize the reliability value computed by the SOVA.
Definition at line 468 of file SISO.h.
References SOVA_scaling_factor.
void tr::SISO::set_sova_threshold (const double & threshold) [inline]
Sets the threshold value used to limit the reliability value computed by SOVA.
Definition at line 473 of file SISO.h.
References SOVA_threshold.
void tr::SISO::set_st_block_code (const int & Q, const itpp::cmat & A, const itpp::cmat & B, const int & N) [inline]
Sets Space-Time block code parameters.
ST block codes are generated using Hassibi's model.
Parameters:
Q the number of symbols per block
A generator matrices
B of the ST block code
N the number of reception antennas
Definition at line 559 of file SISO.h.
References block_duration, nb_em_ant, nb_rec_ant, ST_gen1, ST_gen2, and symbols_block.
Referenced by main(), and mexFunction().
void tr::SISO::set_tail (const bool & in_tail) [inline]
Signals whether the trellis used in the MAP algorithm is terminated or not (only for convolutional codes and multipath channels).
If the input value is true, the trellis is terminated. In order to terminate the trellis an ending bit tail is added to the input stream of the encoder.
Definition at line 458 of file SISO.h.
References tail.
Referenced by equalizer(), main(), mexFunction(), nsc(), and rsc().
void tr::SISO::set_viterbi_hard_output_flag (const bool & flag) [inline]
Sets the Viterbi algorithm hard output flag (true when only the hard output is needed).
Definition at line 485 of file SISO.h.
References Viterbi_hard_output_flag.
Referenced by mexFunction().
void tr::SISO::set_viterbi_scaling_factors (const double & matching_scaling_factor, const double & nonmatching_scaling_factor) [inline]
Sets the Viterbi algorithm scaling factors.
Parameters:
matching_scaling_factor scaling factor for matching bits
nonmatching_scaling_factor scaling factor for non matching bits
Definition at line 478 of file SISO.h.
References Viterbi_scaling_factor.
void tr::SISO::set_viterbi_win_len (const int & win_len) [inline]
Sets the length of the trellis used by the SOVA.
Definition at line 463 of file SISO.h.
References Viterbi_win_len.
Referenced by main(), and mexFunction().
void tr::SISO::sGA (itpp::vec & extrinsic_data, const itpp::cmat & rec_sig, const itpp::vec & apriori_data) [private]
SISO::demapper using simplified Gaussian Approximation (sGA) algorithm.
Definition at line 314 of file SISO_dem.cpp.
References apriori_data, block_duration, c_impulse_response, EquivCh(), EquivRecSig(), extrinsic_data, find_half_const(), nb_bits_symb, nb_rec_ant, sigma2, symbols_block, and temp.
Referenced by demapper().
void tr::SISO::sGCD (itpp::mat & extrinsic_data, const itpp::vec & rec_sig, const itpp::mat & apriori_data) [private]
SISO::mud using simplified Gaussian Chip Detector (sGCD).
simplified Gaussian Chip Detector for IDMA systems
This algorithm is simplified and uses much less memory than its counterpart, the GCD. Recommended to use in most cases.
Definition at line 388 of file SISO_mud.cpp.
References extrinsic_data, impulse_response, n, sigma2, and zpFIRfilter().
Referenced by mud().
void tr::SISO::zfPIC (itpp::vec & extrinsic_data, const itpp::cmat & rec_sig, const itpp::vec & apriori_data) [private]
SISO::demapper using ZF Parallel Interference Canceller (PIC).
Definition at line 568 of file SISO_dem.cpp.
References apriori_data, block_duration, c_impulse_response, EquivCh(), EquivRecSig(), Es, extrinsic_data, find_half_const(), nb_bits_symb, nb_rec_ant, sigma2, symbols_block, and temp.
Referenced by demapper().
void tr::SISO::zpFIRfilter (itpp::vec & filt, const itpp::vec & h, const itpp::vec & sig) [private]
FIR filter for a zero padded signals (zeros are added at the end of the signal, where is the order of the filter).
Parameters:
filt filtered signal
h filter impulse response
sig signal to filter
Definition at line 42 of file SISO_mud.cpp.
References n.
Referenced by sGCD().
Member Data Documentation
itpp::bmat tr::SISO::bin_constellation [private]
Binary constellation.
Definition at line 344 of file SISO.h.
Referenced by Alamouti_maxlogMAP(), demapper(), demodulator_logMAP(), demodulator_maxlogMAP(), find_half_const(), and set_constellation().
int tr::SISO::block_duration [private]
ST code block duration.
Definition at line 353 of file SISO.h.
Referenced by EquivCh(), EquivRecSig(), GA(), Hassibi_maxlogMAP(), mmsePIC(), set_st_block_code(), sGA(), and zfPIC().
itpp::cmat tr::SISO::c_impulse_response [private]
Complex channel impulse response.
Definition at line 333 of file SISO.h.
Referenced by Alamouti_maxlogMAP(), demapper(), demodulator_logMAP(), demodulator_maxlogMAP(), GA(), Hassibi_maxlogMAP(), mmsePIC(), set_impulse_response(), sGA(), and zfPIC().
struct { ... } tr::SISO::chtrellis [private]
(Hyper) Channel trellis
Referenced by equalizer_logMAP(), equalizer_maxlogMAP(), gen_chtrellis(), gen_hyperTrellis(), and mud_maxlogMAP().
itpp::cvec tr::SISO::constellation [private]
Complex constellation.
Definition at line 342 of file SISO.h.
Referenced by Alamouti_maxlogMAP(), demapper(), demodulator_logMAP(), demodulator_maxlogMAP(), find_half_const(), Hassibi_maxlogMAP(), and set_constellation().
std::string tr::SISO::demapper_method [private]
Demapper method.
Definition at line 359 of file SISO.h.
Referenced by demapper(), set_demapper_method(), and SISO().
itpp::bin* tr::SISO::fm
Definition at line 390 of file SISO.h.
itpp::bmat tr::SISO::gen [private]
Generator polynomials for convolutional codes (CC).
Definition at line 311 of file SISO.h.
Referenced by gen_nsctrellis(), gen_rsctrellis(), nsc(), nsc_logMAP(), nsc_maxlogMAP(), rsc(), rsc_sova(), rsc_viterbi(), and set_generators().
itpp::mat tr::SISO::impulse_response [private]
Real channel impulse response.
Definition at line 331 of file SISO.h.
Referenced by equalizer(), GCD(), gen_chtrellis(), gen_hyperTrellis(), mud(), set_impulse_response(), and sGCD().
int* tr::SISO::input
input
Definition at line 379 of file SISO.h.
std::string tr::SISO::MAP_metric [private]
MAP algorithm metric.
Definition at line 309 of file SISO.h.
Referenced by demapper(), equalizer(), nsc(), rsc(), set_map_metric(), and SISO().
std::string tr::SISO::MUD_method [private]
MUD method.
Definition at line 337 of file SISO.h.
Referenced by mud(), set_mud_method(), and SISO().
int tr::SISO::nb_bits_symb [private]
Number of bits/symbol.
Definition at line 340 of file SISO.h.
Referenced by Alamouti_maxlogMAP(), demodulator_logMAP(), demodulator_maxlogMAP(), find_half_const(), GA(), Hassibi_maxlogMAP(), mmsePIC(), set_constellation(), sGA(), and zfPIC().
int tr::SISO::nb_em_ant [private]
Number of emission antennas.
Definition at line 349 of file SISO.h.
Referenced by EquivCh(), mmsePIC(), and set_st_block_code().
int tr::SISO::nb_rec_ant [private]
Number of reception antennas.
Definition at line 351 of file SISO.h.
Referenced by Alamouti_maxlogMAP(), EquivCh(), EquivRecSig(), GA(), Hassibi_maxlogMAP(), mmsePIC(), set_st_block_code(), sGA(), and zfPIC().
int* tr::SISO::nextState
next states
Definition at line 377 of file SISO.h.
int* tr::SISO::nextStates
next states
Definition at line 388 of file SISO.h.
struct { ... } tr::SISO::nsctrellis [private]
NSC code trellis.
Referenced by gen_nsctrellis(), nsc_logMAP(), and nsc_maxlogMAP().
int tr::SISO::numInputSymbols
number of input symbols
Definition at line 374 of file SISO.h.
int tr::SISO::numStates
number of states
Definition at line 386 of file SISO.h.
double* tr::SISO::output
output
Definition at line 378 of file SISO.h.
double* tr::SISO::PARout
parity output bit
Definition at line 389 of file SISO.h.
itpp::bvec tr::SISO::prec_gen [private]
Precoder generator polynomial.
Definition at line 313 of file SISO.h.
Referenced by equalizer(), gen_chtrellis(), gen_hyperTrellis(), set_precoder_generator(), and SISO().
int* tr::SISO::prevState
previous states
Definition at line 376 of file SISO.h.
int* tr::SISO::prevStates
previous states
Definition at line 387 of file SISO.h.
struct { ... } tr::SISO::rsctrellis [private]
RSC code trellis.
Referenced by gen_rsctrellis(), rsc_logMAP(), rsc_maxlogMAP(), rsc_sova(), and rsc_viterbi().
itpp::bvec tr::SISO::scrambler_pattern [private]
Scrambler pattern.
Definition at line 335 of file SISO.h.
Referenced by descrambler(), nsc_logMAP(), nsc_maxlogMAP(), set_scrambler_pattern(), and SISO().
double tr::SISO::sigma2 [private]
AWGN noise variance.
Definition at line 329 of file SISO.h.
Referenced by Alamouti_maxlogMAP(), demodulator_logMAP(), demodulator_maxlogMAP(), equalizer_logMAP(), equalizer_maxlogMAP(), GA(), Hassibi_maxlogMAP(), mmsePIC(), mud_maxlogMAP(), set_noise(), sGA(), sGCD(), and zfPIC().
double tr::SISO::SOVA_scaling_factor [private]
SOVA scaling factor used to multiply the reliabiliy information.
Definition at line 320 of file SISO.h.
Referenced by rsc_sova(), set_sova_scaling_factor(), and SISO().
double tr::SISO::SOVA_threshold [private]
SOVA threshold used to limit the reliability information.
Definition at line 322 of file SISO.h.
Referenced by rsc_sova(), set_sova_threshold(), and SISO().
itpp::cmat tr::SISO::ST_gen1 [private]
ST generator matrix 1.
Definition at line 355 of file SISO.h.
Referenced by demapper(), EquivCh(), and set_st_block_code().
itpp::cmat tr::SISO::ST_gen2 [private]
ST generator matrix 2.
Definition at line 357 of file SISO.h.
Referenced by demapper(), EquivCh(), and set_st_block_code().
int tr::SISO::stateNb
number of states
Definition at line 375 of file SISO.h.
int tr::SISO::symbols_block [private]
Number of symbols/block.
Definition at line 347 of file SISO.h.
Referenced by EquivCh(), GA(), Hassibi_maxlogMAP(), mmsePIC(), set_st_block_code(), sGA(), and zfPIC().
bool tr::SISO::tail [private]
True if trellis of CC is terminated.
Definition at line 315 of file SISO.h.
Referenced by equalizer_logMAP(), equalizer_maxlogMAP(), mud_maxlogMAP(), nsc_logMAP(), nsc_maxlogMAP(), rsc_logMAP(), rsc_maxlogMAP(), set_tail(), and SISO().
bool tr::SISO::Viterbi_hard_output_flag [private]
Viterbi hard output flag (true when only hard output is needed).
Definition at line 326 of file SISO.h.
Referenced by rsc_viterbi(), set_viterbi_hard_output_flag(), and SISO().
double tr::SISO::Viterbi_scaling_factor[2] [private]
Viterbi scaling factors.
Definition at line 324 of file SISO.h.
Referenced by rsc_viterbi(), set_viterbi_scaling_factors(), and SISO().
int tr::SISO::Viterbi_win_len [private]
Viterbi trellis window length.
Definition at line 318 of file SISO.h.
Referenced by rsc(), set_viterbi_win_len(), and SISO().
The documentation for this class was generated from the following files:
SISO.h
SISO_dem.cpp
SISO_eq.cpp
SISO_mud.cpp
SISO_nsc.cpp
SISO_rsc.cpp