SISO: tr::EXIT Class Reference
tr::EXIT Class Reference
#include <EXIT.h>
Public Member Functions
double apriori_mutual_info (const double &in_sigma2A, const double &lim=100)
Computes the a priori mutual information.
itpp::vec generate_apriori_info (const itpp::bvec &bits)
Generates a priori information assuming a Gaussian distribution of the a priori information.
double extrinsic_mutual_info (const itpp::vec &obs, const itpp::bvec &cond, const int &N=100)
Computes the extrinsic mutual information.
Static Private Member Functions
static double gaussian_fct (const double x)
Static Private Attributes
static double sigma2A
EXtrinsic Information Transfer (EXIT) chart.
Friends
double itpp::quad (double(*f)(double), double a, double b, double tol)
Detailed Description
Definition at line 16 of file EXIT.h.
Member Function Documentation
double tr::EXIT::apriori_mutual_info (const double & in_sigma2A, const double & lim = 100) [inline]
Computes the a priori mutual information.
It is assumed that the a priori information has a Gaussian distribution
Parameters:
in_sigma2A variance of the a priori information
lim [-lim,+lim] is the integration interval (theoretically it should be [-inf,+inf])
Definition at line 22 of file EXIT.h.
References gaussian_fct(), itpp::quad, and sigma2A.
Referenced by main().
double tr::EXIT::extrinsic_mutual_info (const itpp::vec & obs, const itpp::bvec & cond, const int & N = 100)
Computes the extrinsic mutual information.
The conditional Probability Density Function (PDF) of the extrinsic information is estimated using the histogram of the extrinsic information and the knowledge of the emitted bits corresponding to the extrinsic information.
Parameters:
obs extrinsic information obtained from the SISO module output
cond emitted bits corresponding to the extrinsic information
N number of subintervals used to compute the histogram
Definition at line 27 of file EXIT.cpp.
Referenced by main().
static double tr::EXIT::gaussian_fct (const double x) [inline, static, private]
Definition at line 49 of file EXIT.h.
References sigma2A.
Referenced by apriori_mutual_info().
itpp::vec tr::EXIT::generate_apriori_info (const itpp::bvec & bits) [inline]
Generates a priori information assuming a Gaussian distribution of the a priori information.
The variance of the a priori information must be already initialized through EXIT::apriori_mutual_info function. The information generated in this way is used sometimes as intrinsic information at the SISO module input.
Definition at line 33 of file EXIT.h.
References sigma2A.
Referenced by main().
Friends And Related Function Documentation
double itpp::quad (double(*)(double) f, double a, double b, double tol) [friend]
Referenced by apriori_mutual_info().
Member Data Documentation
double tr::EXIT::sigma2A [static, private]
EXtrinsic Information Transfer (EXIT) chart.
Computes the A priori Mutual Information assuming a Gaussian distribution of the a priori information and the Extrinsic Mutual Information between the emitted bits and their extrinsic information
Description:
the a priori mutual information is computed using relation (14)
the extrinsic mutual information is computed by estimating first the conditional Probability Density Functions (PDF), given the emitted bits, and then numerically integrating according to relation (19)
Reference: Stephan ten Brink, ''Convergence behavior of iteratively decoded parallel concatenated codes,`` IEEE Transactions on Communications, oct. 2001
Definition at line 47 of file EXIT.h.
Referenced by apriori_mutual_info(), gaussian_fct(), and generate_apriori_info().
The documentation for this class was generated from the following files:
EXIT.h
EXIT.cpp