SISO: EXIT_pccc.cpp File Reference
EXIT_pccc.cpp File Reference
EXtrinsic Information Transfer (EXIT) chart for Parallel Concatenated Convolutional Codes (PCCCs) of coding rate 1/3.
#include "itpp/itcomm.h"
#include "SISO.h"
#include "EXIT.h"
#include "Progress_Timer.h"
Defines
#define TO_FILE
Functions
int main (void)
Detailed Description
EXtrinsic Information Transfer (EXIT) chart for Parallel Concatenated Convolutional Codes (PCCCs) of coding rate 1/3.
Computes the Transfer Characteristics of the two SISO RSC modules used in the turbo decoder for PCCCs at a given Signal to Noise Ratio (SNR).
Reference: S. ten Brink, ''Convergence behavior of iteratively decoded parallel concatenated codes,`` IEEE Transactions on Communications, vol. 49, pp. 1727-1737, Oct. 2001
Definition in file EXIT_pccc.cpp.
Define Documentation
#define TO_FILE
Definition at line 13 of file EXIT_pccc.cpp.
Function Documentation
int main (void)
Definition at line 28 of file EXIT_pccc.cpp.
References apriori_data, tr::EXIT::apriori_mutual_info(), bits, coded_bits, constraint_length, EbN0_dB, Ec, en, extrinsic_coded, extrinsic_data, tr::EXIT::extrinsic_mutual_info(), filename, gen, tr::EXIT::generate_apriori_info(), map_metric, n, nb_bits, nb_blocks, perm_len, R, tr::SISO::rsc(), tr::SISO::set_generators(), tr::SISO::set_map_metric(), sigma2, tail, threshold(), and threshold_value.