SISO: IDMA.cpp File Reference
IDMA.cpp File Reference
Interleave Division Multiple Access with turbo multiuser detection.
#include "itpp/itcomm.h"
#include "SISO.h"
#include "Progress_Timer.h"
Functions
template<class Num_T >
itpp::Vec< Num_T > kron (const itpp::Vec< Num_T > &in, const itpp::Vec< Num_T > &pattern)
Kronecker operator for vectors (both inputs are seen as column or row vectors).
int main (void)
Detailed Description
Interleave Division Multiple Access with turbo multiuser detection.
Reference: L. Liu and L. Ping, ''Iterative detection of chip interleaved CDMA systems in multipath channels,`` Electronics letters, vol. 40, pp. 884-886, July 2004
Definition in file IDMA.cpp.
Function Documentation
template<class Num_T > itpp::Vec<Num_T> kron (const itpp::Vec< Num_T > & in, const itpp::Vec< Num_T > & pattern) [inline]
Kronecker operator for vectors (both inputs are seen as column or row vectors).
Definition at line 18 of file IDMA.cpp.
References n.
Referenced by main().
int main (void)
Definition at line 35 of file IDMA.cpp.
References bits, coded_bits, constraint_length, tr::SISO::descrambler(), EbN0_dB, Ec, en, filename, gen, inv_perm, kron(), map_metric, tr::SISO::mud(), n, nb_bits, nb_bits_lim, nb_blocks, nb_errors, nb_errors_lim, nb_iter, tr::SISO::nsc(), perm, perm_len, R, rec, rec_bits, tr::SISO::set_generators(), tr::SISO::set_impulse_response(), tr::SISO::set_map_metric(), tr::SISO::set_mud_method(), tr::SISO::set_noise(), tr::SISO::set_scrambler_pattern(), tr::SISO::set_tail(), sigma2, snr_len, threshold(), and threshold_value.