SISO: pccc.m File Reference
pccc.m File Reference
Functions
PCCC Reference: (MAP threshold)
total number of bits in a block (with tail) nb_iter
coding rate (non punctured PCCC) Ec
while ((nb_errors< nb_errors_lim)&&(nb_blocks *perm_len< perm_len_lim))%permutation perm
multiplexer coded_bits (1:3:end)
coded_bits (2:3:end)
coded_bits (3:3:end)
BPSK modulation (1->-1, 0->+1)+AWGN channel rec
form input for SISO blocks dec1_intrinsic_coded (1:2:end)
dec1_intrinsic_coded (2:2:end)
dec2_intrinsic_coded (2:2:end)
threshold apriori_data (apriori_data >threshold)
apriori_data (apriori_data<-threshold)
count errors BER (n, en)
end end blocks(while loop)%compute
BER over all tx blocks BER(show
progress txtprogressbar (en/snr_len)
end figure semilogy (EbN0_dB, BER, 'o-') grid on xlabel('E_b/N_0[dB]') ylabel('BER') save(filename
Variables
map_metric = 'maxlogMAP'
gen = [13 15]
nb_errors_lim = 3000
perm_len_lim = 1e6
perm_len = pow2(16)
number of iterations in the
turbo decoder EbN0_dB = 0:0.1:5
R = 1/3
coded bit energy other parameters bin_gen = de2bi(base2dec(int2str(gen.'), 8), 'left-msb')
constraint_len = size (bin_gen, 2)
sova_win_len = 5*constraint_len
filename = ['Res/pccc_' map_metric '_' num2str(gen(1)) '_' num2str(gen(2)) '.mat']
sigma2 = (0.5*Ec/R)*10.^(-EbN0_dB/10)
N0 perm = zeros(1, perm_len)
inv_perm = zeros(1, perm_len)
cod_bits_len = perm_len*length(gen)
rec_len = perm_len/R
coded_bits = zeros(1, rec_len)
rec = zeros(1, rec_len)
dec1_intrinsic_coded = zeros(1, cod_bits_len)
dec2_intrinsic_coded = zeros(1, cod_bits_len)
extrinsic_coded = zeros(1, perm_len)
extrinsic_data = zeros(1, perm_len)
snr_len = length(EbN0_dB)
BER = zeros(nb_iter, snr_len)
Recursive Systematic
Convolutional Code trellis trellis = poly2trellis(constraint_len, gen, gen(1))
main loop txtprogressbar
for en
nb_blocks = 0
inverse permutation [ignore, inv_perm] = sort(perm)
bits generation bits = randint(1, perm_len, 2)
parallel concatenated
convolutional code cod1_bits = convenc(bits, trellis, 0)
initial state is zero cod2_bits = convenc(bits(perm), trellis, 0)
turbo decoder apriori_data = zeros(1, perm_len)
a priori LLR for information
bits for n
second decoder [extrinsic_coded extrinsic_data]
rec_bits = double(apriori_data(inv_perm)>0)
end end iterations nb_errors = nb_errors+nnz(bits-rec_bits(1:perm_len))
end figure nb_iter
Function Documentation
apriori_data ()
threshold apriori_data (apriori_data , threshold)
count errors BER (n , en)
total number of bits in a block (with tail)
coded_bits (3:3:end)
coded_bits (2:3:end)
multiplexer coded_bits (1:3:end)
dec1_intrinsic_coded (2:2:end)
form input for SISO blocks dec1_intrinsic_coded (1:2:end)
dec2_intrinsic_coded (2:2:end)
BPSK modulation (1->- 1, 0->+ 1)
coding rate (non punctured PCCC)
PCCC Reference: (MAP threshold) [virtual]
end figure semilogy (EbN0_dB , BER , 'o-')
end end blocks (while loop) %compute BER over all tx blocks BER(show progress txtprogressbar (en/ snr_len)
while ((nb_errors< nb_errors_lim)&&(nb_blocks *perm_len< perm_len_lim))
Variable Documentation
deinterleave for the next iteration apriori_data = zeros(1, perm_len)
Definition at line 79 of file pccc.m.
Referenced by tr::SISO::Alamouti_maxlogMAP(), tr::SISO::demodulator_logMAP(), tr::SISO::demodulator_maxlogMAP(), tr::SISO::GA(), tr::SISO::Hassibi_maxlogMAP(), main(), mexFunction(), tr::SISO::mmsePIC(), tr::SISO::mud_maxlogMAP(), tr::SISO::rsc_sova(), tr::SISO::rsc_viterbi(), tr::SISO::sGA(), and tr::SISO::zfPIC().
end figure BER = zeros(nb_iter, snr_len)
Definition at line 42 of file pccc.m.
coded bit energy other parameters bin_gen = de2bi(base2dec(int2str(gen.'), 8), 'left-msb')
Definition at line 26 of file pccc.m.
Referenced by mexFunction().
bits generation bits = randint(1, perm_len, 2)
Definition at line 59 of file pccc.m.
Referenced by main().
parallel concatenated convolutional code cod1_bits = convenc(bits, trellis, 0)
Definition at line 62 of file pccc.m.
Referenced by main().
initial state is zero cod2_bits = convenc(bits(perm), trellis, 0)
Definition at line 63 of file pccc.m.
Referenced by main().
cod_bits_len = perm_len*length(gen)
Definition at line 33 of file pccc.m.
Referenced by main().
coded_bits = zeros(1, rec_len)
Definition at line 35 of file pccc.m.
Referenced by main().
constraint_len = size (bin_gen, 2)
Definition at line 27 of file pccc.m.
dec1_intrinsic_coded = zeros(1, cod_bits_len)
Definition at line 37 of file pccc.m.
Referenced by main().
dec2_intrinsic_coded = zeros(1, cod_bits_len)
Definition at line 38 of file pccc.m.
Referenced by main().
second decoder[extrinsic_coded extrinsic_data]
Initial value:
 ...
                C_SISOrsc(dec2_intrinsic_coded, apriori_data, bin_gen, 0, map_metric)
Definition at line 91 of file pccc.m.
end figure EbN0_dB = 0:0.1:5
Definition at line 21 of file pccc.m.
Referenced by main().
for en
Initial value:
1:snr_len
    nb_errors = 0
Definition at line 49 of file pccc.m.
Referenced by main().
extrinsic_coded = zeros(1, perm_len)
Definition at line 39 of file pccc.m.
Referenced by main(), mexFunction(), and tr::SISO::rsc_viterbi().
no tail extrinsic_data = zeros(1, perm_len)
Definition at line 40 of file pccc.m.
Referenced by tr::SISO::Alamouti_maxlogMAP(), tr::SISO::demodulator_logMAP(), tr::SISO::demodulator_maxlogMAP(), tr::SISO::GA(), tr::SISO::GCD(), tr::SISO::Hassibi_maxlogMAP(), main(), mexFunction(), tr::SISO::mmsePIC(), tr::SISO::mud_maxlogMAP(), tr::SISO::rsc_sova(), tr::SISO::rsc_viterbi(), tr::SISO::sGA(), tr::SISO::sGCD(), and tr::SISO::zfPIC().
filename = ['Res/pccc_' map_metric '_' num2str(gen(1)) '_' num2str(gen(2)) '.mat']
Definition at line 29 of file pccc.m.
Referenced by main().
end figure gen = [13 15]
Definition at line 14 of file pccc.m.
Referenced by main().
inv_perm = zeros(1, perm_len)
Definition at line 32 of file pccc.m.
Referenced by main().
map_metric = 'maxlogMAP'
Definition at line 13 of file pccc.m.
Referenced by main(), and mexFunction().
a priori LLR for information bits for n
Initial value:
1:nb_iter
            %first decoder
            [extrinsic_coded extrinsic_data] = ...
                C_SISOrsc(dec1_intrinsic_coded, apriori_data, bin_gen, 0, map_metric)
Definition at line 80 of file pccc.m.
Referenced by tr::SISO::Alamouti_maxlogMAP(), tr::SISO::descrambler(), tr::STC::diag_pow(), tr::SISO::equalizer_logMAP(), tr::SISO::equalizer_maxlogMAP(), tr::SISO::EquivCh(), tr::SISO::find_half_const(), tr::SISO::GCD(), tr::SISO::gen_chtrellis(), tr::SISO::gen_hyperTrellis(), tr::SISO::gen_nsctrellis(), tr::SISO::gen_rsctrellis(), tr::SISO::Hassibi_maxlogMAP(), kron(), main(), tr::STC::mat_pow(), tr::SISO::mud_maxlogMAP(), tr::SISO::nsc_logMAP(), tr::SISO::nsc_maxlogMAP(), tr::SISO::rsc_logMAP(), tr::SISO::rsc_maxlogMAP(), tr::SISO::set_constellation(), tr::SISO::set_generators(), tr::SISO::set_scrambler_pattern(), tr::SISO::sGCD(), tr::threshold(), and tr::SISO::zpFIRfilter().
get number of errors at the last iteration nb_blocks = 0
Definition at line 51 of file pccc.m.
Referenced by main().
end end iterations nb_errors = nb_errors+nnz(bits-rec_bits(1:perm_len))
Definition at line 110 of file pccc.m.
Referenced by main().
end figure nb_errors_lim = 3000
Definition at line 17 of file pccc.m.
Referenced by main().
end figure nb_iter
Definition at line 127 of file pccc.m.
Referenced by main().
N0 perm = zeros(1, perm_len)
Definition at line 31 of file pccc.m.
Referenced by main().
end figure perm_len = pow2(16)
Definition at line 19 of file pccc.m.
Referenced by main().
perm_len_lim = 1e6
Definition at line 18 of file pccc.m.
inverse permutation[ignore, inv_perm] = sort(perm)
Definition at line 56 of file pccc.m.
end figure R = 1/3
Definition at line 22 of file pccc.m.
Referenced by main().
rec = zeros(1, rec_len)
Definition at line 36 of file pccc.m.
Referenced by main().
rec_bits = double(apriori_data(inv_perm)>0)
Definition at line 97 of file pccc.m.
Referenced by main().
rec_len = perm_len/R
Definition at line 34 of file pccc.m.
Referenced by main().
sigma2 = (0.5*Ec/R)*10.^(-EbN0_dB/10)
Definition at line 30 of file pccc.m.
Referenced by main(), and mexFunction().
snr_len = length(EbN0_dB)
Definition at line 41 of file pccc.m.
Referenced by main().
sova_win_len = 5*constraint_len
Definition at line 28 of file pccc.m.
Recursive Systematic Convolutional Code trellis trellis = poly2trellis(constraint_len, gen, gen(1))
Definition at line 45 of file pccc.m.
main loop txtprogressbar
Definition at line 48 of file pccc.m.