SISO: sccc.m File Reference
sccc.m File Reference
Functions
SCCC threshold ()
if (int32(nb_bits)~=nb_bits)||(int32(rec_len)~
while ((nb_errors< nb_errors_lim)&&(nb_blocks *perm_len< nb_bits_lim))%permutation perm
BPSK modulation (1->-1, 0->+1)+AWGN channel rec
no tail deinterleave outer_code_intrinsic_coded (expanded_puncturing_pattern)
no tail deinterleave for the
next iteration temp (1:2:end)
temp (2:2:end)
threshold inner_code_apriori_data (inner_code_apriori_data >threshold)
inner_code_apriori_data (inner_code_apriori_data<-threshold)
BER (n, en)
end end blocks(while loop)%compute
BER over all tx blocks BER(show
progress txtprogressbar (en/snr_len)
end figure semilogy (EbN0_dB, BER, 'o-') grid on xlabel('E_b/N_0[dB]') ylabel('BER') save(filename
Variables
map_metric = 'logMAP'
gen = [7 5]
recursive polynomial first outer_code_puncturing_pattern = [1 1 1 1]
nb_errors_lim = 3000
nb_bits_lim = 1e6
perm_len = 3*pow2(15)
total number of bits in a block nb_iter = 10
number of iterations in the
turbo decoder EbN0_dB = 0:0.1:5
Ec = 1
coded bit energy other parameters bin_gen = de2bi(base2dec(int2str(gen.'), 8), 'left-msb')
code_outputs = length(gen)
outer_code_rate
inner_code_rate = 1/length(gen)
R = outer_code_rate*inner_code_rate
coding rate of the SCCC constraint_len = size (bin_gen, 2)
sova_win_len = 5*constraint_len
filename = ['Res/sccc5_' map_metric '_' num2str(gen(1)) '_' num2str(gen(2)) '.mat']
sigma2 = (0.5*Ec/R)*10.^(-EbN0_dB/10)
N0 perm = zeros(1, perm_len)
inv_perm = zeros(1, perm_len)
nb_bits = perm_len*outer_code_rate
rec_len = perm_len/inner_code_rate
end rec = zeros(1, rec_len)
snr_len = length(EbN0_dB)
BER = zeros(nb_iter, snr_len)
expanded_puncturing_pattern
inner_code_extrinsic_data = zeros(1, perm_len)
outer_code_apriori_data = zeros(1, nb_bits)
outer_code_intrinsic_coded = zeros(1, nb_bits*code_outputs)
Recursive Systematic
Convolutional Code trellis trellis = poly2trellis(constraint_len, gen, gen(1))
main loop txtprogressbar
for en
nb_blocks = 0
inverse permutation [ignore, inv_perm] = sort(perm)
bits generation bits = randint(1, nb_bits, 2)
serial concatenated
convolutional code temp = convenc(bits, trellis, 0)
initial state is zero outer_code_bits = temp(expanded_puncturing_pattern)
puncturing inner_code_bits = convenc(outer_code_bits(perm), trellis, 0)
turbo decoder inner_code_apriori_data = zeros(1, perm_len)
a priori LLR for information bits inner_code_intrinsic_coded = (-2/sigma2(en))*rec
for n
outer decoder [outer_code_extrinsic_parity outer_code_extrinsic_data]
temp2 = temp(expanded_puncturing_pattern)
count errors rec_bits = double(outer_code_extrinsic_data>0)
end end iterations nb_errors = nb_errors+nnz(bits-rec_bits)
Function Documentation
BER (n , en)
if (int32(nb_bits)~ = nb_bits)
Referenced by tr::SISO::equalizer_maxlogMAP().
inner_code_apriori_data ()
threshold inner_code_apriori_data (inner_code_apriori_data , threshold)
BPSK modulation (1->- 1, 0->+ 1)
no tail deinterleave outer_code_intrinsic_coded (expanded_puncturing_pattern)
end figure semilogy (EbN0_dB , BER , 'o-')
temp (2:2:end)
no tail deinterleave for the next iteration temp (1:2:end)
SCCC threshold () [virtual]
Referenced by main().
end end blocks (while loop) %compute BER over all tx blocks BER(show progress txtprogressbar (en/ snr_len)
while ((nb_errors< nb_errors_lim)&&(nb_blocks *perm_len< nb_bits_lim))
Variable Documentation
end figure BER = zeros(nb_iter, snr_len)
Definition at line 41 of file sccc.m.
coded bit energy other parameters bin_gen = de2bi(base2dec(int2str(gen.'), 8), 'left-msb')
Definition at line 21 of file sccc.m.
bits generation bits = randint(1, nb_bits, 2)
Definition at line 63 of file sccc.m.
code_outputs = length(gen)
Definition at line 22 of file sccc.m.
coding rate of the SCCC constraint_len = size (bin_gen, 2)
Definition at line 27 of file sccc.m.
outer decoder[outer_code_extrinsic_parity outer_code_extrinsic_data]
Initial value:
 ...
                C_SISOrsc(outer_code_intrinsic_coded, outer_code_apriori_data, bin_gen, 0, map_metric)
Definition at line 87 of file sccc.m.
end figure EbN0_dB = 0:0.1:5
Definition at line 17 of file sccc.m.
Ec = 1
Definition at line 18 of file sccc.m.
Referenced by main().
for en
Initial value:
1:snr_len
    nb_errors = 0
Definition at line 53 of file sccc.m.
expanded_puncturing_pattern
Initial value:
 logical(kron(ones(1, code_outputs*nb_bits/length(outer_code_puncturing_pattern)), ...
    outer_code_puncturing_pattern))
Definition at line 42 of file sccc.m.
filename = ['Res/sccc5_' map_metric '_' num2str(gen(1)) '_' num2str(gen(2)) '.mat']
Definition at line 29 of file sccc.m.
end figure gen = [7 5]
Definition at line 11 of file sccc.m.
inner_code_apriori_data = zeros(1, perm_len)
Definition at line 74 of file sccc.m.
puncturing inner_code_bits = convenc(outer_code_bits(perm), trellis, 0)
Definition at line 68 of file sccc.m.
inner_code_extrinsic_data = zeros(1, perm_len)
Definition at line 44 of file sccc.m.
a priori LLR for information bits inner_code_intrinsic_coded = (-2/sigma2(en))*rec
Definition at line 75 of file sccc.m.
inner_code_rate = 1/length(gen)
Definition at line 25 of file sccc.m.
inv_perm = zeros(1, perm_len)
Definition at line 32 of file sccc.m.
map_metric = 'logMAP'
Definition at line 10 of file sccc.m.
for n
Initial value:
1:nb_iter
            %inner decoder
            [inner_code_extrinsic_parity inner_code_extrinsic_data] = ...
                C_SISOrsc(inner_code_intrinsic_coded, inner_code_apriori_data, bin_gen, 0, map_metric)
Definition at line 76 of file sccc.m.
nb_bits = perm_len*outer_code_rate
Definition at line 33 of file sccc.m.
Referenced by tr::SISO::descrambler(), and main().
end figure nb_bits_lim = 1e6
Definition at line 14 of file sccc.m.
Referenced by main().
get number of errors at the last iteration nb_blocks = 0
Definition at line 55 of file sccc.m.
end end iterations nb_errors = nb_errors+nnz(bits-rec_bits)
Definition at line 105 of file sccc.m.
end figure nb_errors_lim = 3000
Definition at line 13 of file sccc.m.
end figure nb_iter = 10
Definition at line 16 of file sccc.m.
outer_code_apriori_data = zeros(1, nb_bits)
Definition at line 45 of file sccc.m.
initial state is zero outer_code_bits = temp(expanded_puncturing_pattern)
Definition at line 67 of file sccc.m.
outer_code_intrinsic_coded = zeros(1, nb_bits*code_outputs)
Definition at line 46 of file sccc.m.
recursive polynomial first outer_code_puncturing_pattern = [1 1 1 1]
Definition at line 12 of file sccc.m.
outer_code_rate
Initial value:
 (length(outer_code_puncturing_pattern)/code_outputs)/...
    length(find(outer_code_puncturing_pattern~=0))
Definition at line 23 of file sccc.m.
N0 perm = zeros(1, perm_len)
Definition at line 31 of file sccc.m.
end figure perm_len = 3*pow2(15)
Definition at line 15 of file sccc.m.
inverse permutation[ignore, inv_perm] = sort(perm)
Definition at line 60 of file sccc.m.
end figure R = outer_code_rate*inner_code_rate
Definition at line 26 of file sccc.m.
end rec = zeros(1, rec_len)
Definition at line 39 of file sccc.m.
count errors rec_bits = double(outer_code_extrinsic_data>0)
Definition at line 101 of file sccc.m.
rec_len = perm_len/inner_code_rate
Definition at line 34 of file sccc.m.
sigma2 = (0.5*Ec/R)*10.^(-EbN0_dB/10)
Definition at line 30 of file sccc.m.
snr_len = length(EbN0_dB)
Definition at line 40 of file sccc.m.
sova_win_len = 5*constraint_len
Definition at line 28 of file sccc.m.
serial concatenated convolutional code temp = convenc(bits, trellis, 0)
Definition at line 66 of file sccc.m.
Referenced by tr::SISO::Alamouti_maxlogMAP(), tr::SISO::demodulator_logMAP(), tr::SISO::demodulator_maxlogMAP(), tr::SISO::EquivCh(), tr::SISO::find_half_const(), tr::SISO::GA(), tr::STC::Hassibi_block_code(), tr::STC::Hassibi_encode(), tr::SISO::Hassibi_maxlogMAP(), tr::SISO::mmsePIC(), tr::SISO::sGA(), and tr::SISO::zfPIC().
temp2 = temp(expanded_puncturing_pattern)
Definition at line 93 of file sccc.m.
Recursive Systematic Convolutional Code trellis trellis = poly2trellis(constraint_len, gen, gen(1))
Definition at line 49 of file sccc.m.
main loop txtprogressbar
Definition at line 52 of file sccc.m.