SISO: TC_mud.cpp File Reference
TC_mud.cpp File Reference
Transfer Characteristic (TC) for SISO MUD module.
#include "itpp/itcomm.h"
#include "SISO.h"
#include "EXIT.cpp"
#include "Progress_Timer.h"
Defines
#define TO_FILE
#define USE_PRECODER
#define AWGN_CHANNEL
Functions
int main (void)
Detailed Description
Transfer Characteristic (TC) for SISO MUD module.
Reference: L. Liu and L. Ping, ''Iterative detection of chip interleaved CDMA systems in multipath channels,`` Electronics letters, vol. 40, pp. 884-886, July 2004
Definition in file TC_mud.cpp.
Define Documentation
#define AWGN_CHANNEL
Definition at line 11 of file TC_mud.cpp.
#define TO_FILE
Definition at line 9 of file TC_mud.cpp.
#define USE_PRECODER
Definition at line 10 of file TC_mud.cpp.
Function Documentation
int main (void)
Definition at line 26 of file TC_mud.cpp.
References tr::EXIT::apriori_mutual_info(), EbN0_dB, Ec, en, tr::EXIT::extrinsic_mutual_info(), filename, tr::EXIT::generate_apriori_info(), tr::SISO::mud(), nb_blocks, perm_len, R, rec, tr::SISO::set_impulse_response(), tr::SISO::set_mud_method(), tr::SISO::set_noise(), tr::SISO::set_precoder_generator(), sigma2, threshold(), and threshold_value.