SISO: TC_descrambler.cpp File Reference
TC_descrambler.cpp File Reference
Transfer Characteristic (TC) for SISO descrambler module.
#include "itpp/itcomm.h"
#include "SISO.h"
#include "EXIT.h"
#include "Progress_Timer.h"
Defines
#define TO_FILE
Functions
itpp::bvec kron (const itpp::bvec &in, const itpp::bvec &pattern)
Kronecker operator for binary vectors.
int main (void)
Detailed Description
Transfer Characteristic (TC) for SISO descrambler module.
Reference: L. Liu and L. Ping, ''Iterative detection of chip interleaved CDMA systems in multipath channels,`` Electronics letters, vol. 40, pp. 884-886, July 2004
Definition in file TC_descrambler.cpp.
Define Documentation
#define TO_FILE
Definition at line 9 of file TC_descrambler.cpp.
Function Documentation
itpp::bvec kron (const itpp::bvec & in, const itpp::bvec & pattern)
Kronecker operator for binary vectors.
Definition at line 25 of file TC_descrambler.cpp.
References n.
int main (void)
Definition at line 39 of file TC_descrambler.cpp.
References tr::EXIT::apriori_mutual_info(), bits, tr::SISO::descrambler(), en, tr::EXIT::extrinsic_mutual_info(), filename, tr::EXIT::generate_apriori_info(), kron(), nb_bits, nb_blocks, perm_len, and tr::SISO::set_scrambler_pattern().