SISO: tr::STC Class Reference
tr::STC Class Reference
#include <STC.h>
Public Member Functions
void setup (const int &in_em_antennas, const int &in_channel_uses, const std::string &in_code_name, const int &in_const_size)
Setup ST block codes (Hassibi's method is used).
itpp::cmat encode (const itpp::cvec &symb)
Encodes input symbols according to specified ST code.
const int get_nb_symbols_per_block (void) const
Gets the number of symbols per ST code block.
const itpp::cmat get_1st_gen_matrix (void) const
Gets the first generator matrix of the ST code following Hassibi's approach.
const itpp::cmat get_2nd_gen_matrix (void) const
Gets the second generator matrix of the ST code following Hassibi's approach.
const int get_nb_em_antennas (void) const
Gets the number of emission antennas.
const int get_channel_uses (void) const
Gets the number of channel uses (ST block code duration [symbols]).
Private Member Functions
void Hassibi_block_code (void)
Space Time block Codes (STC).
itpp::cmat Hassibi_encode (const itpp::cvec &symb)
itpp::cmat diag_pow (const itpp::cmat &in_mat, const double &in_exp)
itpp::mat mat_pow (const itpp::mat &in_mat, const int &in_exp)
Private Attributes
int symb_block
int const_size
itpp::cmat A
itpp::cmat B
int em_antennas
int channel_uses
std::string code_name
Detailed Description
Definition at line 16 of file STC.h.
Member Function Documentation
itpp::cmat tr::STC::diag_pow (const itpp::cmat & in_mat, const double & in_exp) [inline, private]
Definition at line 534 of file STC.cpp.
References n.
Referenced by Hassibi_block_code().
itpp::cmat tr::STC::encode (const itpp::cvec & symb) [inline]
Encodes input symbols according to specified ST code.
Definition at line 29 of file STC.h.
References Hassibi_encode().
Referenced by main().
const itpp::cmat tr::STC::get_1st_gen_matrix (void) const [inline]
Gets the first generator matrix of the ST code following Hassibi's approach.
Definition at line 39 of file STC.h.
References A.
Referenced by main().
const itpp::cmat tr::STC::get_2nd_gen_matrix (void) const [inline]
Gets the second generator matrix of the ST code following Hassibi's approach.
Definition at line 44 of file STC.h.
References B.
Referenced by main().
const int tr::STC::get_channel_uses (void) const [inline]
Gets the number of channel uses (ST block code duration [symbols]).
Definition at line 54 of file STC.h.
References channel_uses.
Referenced by main().
const int tr::STC::get_nb_em_antennas (void) const [inline]
Gets the number of emission antennas.
Definition at line 49 of file STC.h.
References em_antennas.
Referenced by main().
const int tr::STC::get_nb_symbols_per_block (void) const [inline]
Gets the number of symbols per ST code block.
Definition at line 34 of file STC.h.
References symb_block.
Referenced by main().
void tr::STC::Hassibi_block_code (void) [private]
Space Time block Codes (STC).
ST block codes are implemented following Hassibi's approach.
Reference: B. Hassibi and B. M. Hochwald, ''High-rate codes that are linear in space and time,`` IEEE Transactions on Information Theory, vol. 48, pp. 1804-1824, July 2002
Definition at line 24 of file STC.cpp.
References A, B, channel_uses, code_name, const_size, diag_pow(), em_antennas, mat_pow(), symb_block, and temp.
Referenced by setup().
itpp::cmat tr::STC::Hassibi_encode (const itpp::cvec & symb) [private]
Definition at line 514 of file STC.cpp.
References A, B, channel_uses, em_antennas, symb_block, and temp.
Referenced by encode().
itpp::mat tr::STC::mat_pow (const itpp::mat & in_mat, const int & in_exp) [inline, private]
Definition at line 545 of file STC.cpp.
References n.
Referenced by Hassibi_block_code().
void tr::STC::setup (const int & in_em_antennas, const int & in_channel_uses, const std::string & in_code_name, const int & in_const_size) [inline]
Setup ST block codes (Hassibi's method is used).
Definition at line 20 of file STC.h.
References channel_uses, code_name, const_size, em_antennas, and Hassibi_block_code().
Referenced by main().
Member Data Documentation
itpp::cmat tr::STC::A [private]
Definition at line 65 of file STC.h.
Referenced by get_1st_gen_matrix(), Hassibi_block_code(), and Hassibi_encode().
itpp::cmat tr::STC::B [private]
Definition at line 66 of file STC.h.
Referenced by get_2nd_gen_matrix(), Hassibi_block_code(), and Hassibi_encode().
int tr::STC::channel_uses [private]
Definition at line 68 of file STC.h.
Referenced by get_channel_uses(), Hassibi_block_code(), Hassibi_encode(), and setup().
std::string tr::STC::code_name [private]
Definition at line 69 of file STC.h.
Referenced by Hassibi_block_code(), and setup().
int tr::STC::const_size [private]
Definition at line 64 of file STC.h.
Referenced by Hassibi_block_code(), and setup().
int tr::STC::em_antennas [private]
Definition at line 67 of file STC.h.
Referenced by get_nb_em_antennas(), Hassibi_block_code(), Hassibi_encode(), and setup().
int tr::STC::symb_block [private]
Definition at line 63 of file STC.h.
Referenced by get_nb_symbols_per_block(), Hassibi_block_code(), and Hassibi_encode().
The documentation for this class was generated from the following files:
STC.h
STC.cpp