SISO: tr Namespace Reference
tr Namespace Reference
turbo receivers workspace
Classes
class SISO
Soft Input Soft Output (SISO) modules.
class EXIT
class STC
Functions
double threshold (const double &x, const double &value)
itpp::vec threshold (const itpp::vec &in, const double &value)
itpp::mat threshold (const itpp::mat &in, const double &value)
Detailed Description
turbo receivers workspace
Function Documentation
itpp::mat tr::threshold (const itpp::mat & in, const double & value) [inline]
Definition at line 771 of file SISO.h.
References n, and threshold().
itpp::vec tr::threshold (const itpp::vec & in, const double & value) [inline]
Definition at line 762 of file SISO.h.
References n, and threshold().
double tr::threshold (const double & x, const double & value) [inline]
Definition at line 755 of file SISO.h.
Referenced by tr::SISO::rsc_sova(), and threshold().