SISO: STBICM.cpp File Reference
STBICM.cpp File Reference
Space Time Bit Interleaved Coded Modulation (ST BICM).
#include "itpp/itcomm.h"
#include "SISO.h"
#include "STC.h"
#include "Progress_Timer.h"
Defines
#define TO_FILE
Functions
int main (void)
Detailed Description
Space Time Bit Interleaved Coded Modulation (ST BICM).
Implements ST BICM using a turbo receiver with a SISO demapper module and a SISO NSC module.
Reference: B. Cristea, ''Turbo receivers for Space-Time BICM``, to be published in IEEE Transactions on Wireless Communications
Definition in file STBICM.cpp.
Define Documentation
#define TO_FILE
Definition at line 10 of file STBICM.cpp.
Function Documentation
int main (void)
Definition at line 25 of file STBICM.cpp.
References bits, coded_bits, constraint_length, tr::SISO::demapper(), demapper_method, EbN0_dB, en, tr::STC::encode(), Es, filename, gen, tr::STC::get_1st_gen_matrix(), tr::STC::get_2nd_gen_matrix(), tr::STC::get_channel_uses(), tr::STC::get_nb_em_antennas(), tr::STC::get_nb_symbols_per_block(), inv_perm, kron(), map_metric, n, nb_bits_lim, nb_blocks, nb_errors, nb_errors_lim, nb_iter, nb_symb, tr::SISO::nsc(), nsc_apriori_data, perm, perm_len, R, rec, rec_bits, tr::SISO::set_constellation(), tr::SISO::set_demapper_method(), tr::SISO::set_generators(), tr::SISO::set_impulse_response(), tr::SISO::set_map_metric(), tr::SISO::set_noise(), tr::SISO::set_st_block_code(), tr::STC::setup(), sigma2, snr_len, threshold(), and threshold_value.